model = "gpt-5.4"
model_reasoning_effort = "xhigh"
plan_mode_reasoning_effort = "xhigh"

[mcp_servers.mcp-nixos]
type = "stdio"
command = "mcp-nixos"
startup_timeout_sec = 60

[mcp_servers.mcp-nixos.tools.nix]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.nix_versions]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.nixos_channels]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.darwin_stats]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.home_manager_stats]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.nixos_search]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.home_manager_search]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.darwin_search]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.home_manager_options_by_prefix]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.home_manager_info]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.nixos_info]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.darwin_options_by_prefix]
approval_mode = "approve"

[mcp_servers.mcp-nixos.tools.darwin_info]
approval_mode = "approve"
