[ilma4-main]
type = sftp
host = ilma4-main
key_use_agent = true
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[ilma4-bkp]
type = sftp
host = ilma4-bkp
key_use_agent = true
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[apal-server]
type = sftp
host = nvc00731.amt.labs.intellij.net
user = malakhov
md5sum_command = md5sum
sha1sum_command = sha1sum
shell_type = unix

