[laat]
type = sftp
host = laat.local
key_use_agent = true
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

[hetzer-storage]
type = sftp
host = u478838.your-storagebox.de
user = u478838
port = 22
key_use_agent = true
shell_type = unix
md5sum_command = none
sha1sum_command = none

