# .sops.yaml

keys:
  - &backup-bitwarden age1j2lwuh9uk9fufuclqvperfx4p79dy7slclqh89cch4z89w670daqv9urkj
  - &quicksilver age1gyjjhhednqc6ev57rec2wk0lqg3kadgujge7lcuudezlkjq7yqys4zck7h
  - &laat age1j2lwuh9uk9fufuclqvperfx4p79dy7slclqh89cch4z89w670daqv9urkj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|txt|bin|conf|crt|key)$
    key_groups:
      - age:
          - *backup-bitwarden
          - *quicksilver
          - *laat
