# .sops.yaml

keys:
  - &primary age1y0rfvrvhwraualay2kwv0ungf3m97pp8pkz5xe9hz40pgre26enqd7s6u4
  - &quicksilver-home age1h5uwefvz7zw4a0m9rqspsy050vzu9zcveyjysv6ujcw7dcmkk32qv9jwcf
  - &laat age1h5uwefvz7zw4a0m9rqspsy050vzu9zcveyjysv6ujcw7dcmkk32qv9jwcf
  - &quicksilver age1c9dtgx24j73tga3m24e8mk634uzs6gun6sgvsrsqrrc7jxa8cazsp5xneu
  - &i4-torrent-vm age1mws4zc90dpjln5hw6zm9kvxa6z5kpjppwglph30xseplwxhjmpfq2ewu8x
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|txt|bin|conf|crt|key)$
    key_groups:
      - age:
          - *quicksilver
          - *primary
          - *quicksilver-home
          - *laat
          - *i4-torrent-vm
