# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [
    "igc" # ethernet during boot
  ];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/76a184dc-385c-4f62-8ddd-90656ba787e5";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/c91d9c3f-3cda-4028-ab27-2f41e35ba272";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/fe7ccc35-d3d4-4573-827e-2ec637f16754";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/F9AD-C657";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/f86b7490-3309-44ad-876a-50a8578012b0";
    fsType = "btrfs";
    options = ["compression=zstd" "nofail" "x-systemd.mount-timeout=5s"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
