# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" "rtsx_usb_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd:1"];
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/bf83ad9a-cbb2-448c-b4a4-bb47b03b7632";
    bypassWorkqueues = true; # improve performance on ssd
    allowDiscards = true; # allow trim
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd:1"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd:1"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/e4f9c22e-4666-45f4-ba9e-0898431d872a";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/4B0C-A30B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/mnt/ssd256" = {
    device = "/dev/disk/by-uuid/b043e463-7643-47a9-8c9e-66a013a714a8";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd:1"];
  };

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/f86b7490-3309-44ad-876a-50a8578012b0";
    depends = [ "/" ];
  };

  /*
  systemd.mounts = [
    {
      description = "Mount USB HDD RAID1 array";
      # wantedBy = ["multi-user.target"]; # uncomment to mount on boot
      after = ["local-fs.target"];
      what = "/dev/disk/by-uuid/f86b7490-3309-44ad-876a-50a8578012b0";
      where = "/mnt/hdd";
      type = "auto";
      options = "defaults";
    }
  ];
  */

  systemd.automounts = [
    {
      description = "Mount USB HDD RAID1 array";
      where = "/mnt/hdd";
      wantedBy = ["multi-user.target"];
      automountConfig = {
        TimeoutIdleSec = "5min"; # auto-umount after 5 minutes of inactivity
      };
    }
  ];

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
