# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/bf83ad9a-cbb2-448c-b4a4-bb47b03b7632";
  boot.initrd.luks.devices."root".bypassWorkqueues = true; # improve performance on ssd
  boot.initrd.luks.devices."root".allowDiscards = true; # allow trim


  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cedf22fb-7b4f-4ed5-9866-6df52db6a986";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:1" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/e4f9c22e-4666-45f4-ba9e-0898431d872a";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/4B0C-A30B";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
