name: "qbittorent-gluetun"
services:
  gluetun:
    image: "qmcgaw/gluetun"
    container_name: gluetun
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${WG_CONFIG}:/gluetun/wireguard/wg0.conf:ro"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - "8080:8080" # qBittorrent web interface
    cap_add:
      - NET_ADMIN
    environment:
      - "VPN_SERVICE_PROVIDER=custom"
      - "VPN_TYPE=wireguard"
    networks:
      qbt:
        ipv4_address: 10.5.0.5
  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: qbittorrent
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/Users/ilma4/Downloads/Torrent/torrent-vm:/downloads"
      - qbittorrent_config:/config/qBittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    healthcheck:
      test:
        - "CMD-SHELL"
        - >
          CURRENT_IP=$(curl -s https://ifconfig.me) &&
          [ "$CURRENT_IP" = "185.68.21.215" ]
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  qbittorrent_config:

networks:
  qbt:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
