#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version = "1"
[global]
prevent-sleep = true # note: https://creativeprojects.github.io/resticprofile/configuration/sleep/index.html
priority = "low"

[default]
repository = "/mnt/hdd/restic-server"
password-file = "/run/secrets/restic/server"

[default.backup]
initialize = true

source = [
  "/srv",
]

# TODO
