services:
  node-exporter:
    image: ${NODE_EXPORTER_IMAGE}
    user: "${NODE_EXPORTER_UID}:${NODE_EXPORTER_GID}"
    container_name: "node-exporter"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
    pid: host
    network_mode: host
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - SYS_TIME
    restart: unless-stopped
