services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-5.1.4
    ports:
      - "8080:8080"
    environment:
      - VPN_ENABLED=true
      - VPN_PROVIDER=wireguard
      - VPN_LAN_NETWORK=10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/qbittorrent/config:/config"
      - "/mnt/hdd/torrent:/downloads"
      - "/home/ilma4/torrents:/ssd-downloads"
      - "/home/ilma4/.config/wg0.conf:/config/wireguard/wg0.conf:ro"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
