version: "3.8"
services:
  stirling-pdf:
    image: docker.io/stirlingtools/stirling-pdf:latest-ultra-lite
    container_name: pdf-tools
    expose:
      - "8080"

    networks:
      reverse_proxy:

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/stirling-pdf/trainingData:/usr/share/tessdata
      - /srv/stirling-pdf/extraConfigs:/configs
      - /srv/stirling-pdf/logs:/logs
      - /srv/stirling-pdf/pipeline:/pipeline
    restart: unless-stopped

networks:
  reverse_proxy:
    external: true
